/*
 * Copyright (c) 2026 Hubble Network, Inc.
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef TEST_VECTORS_H
#define TEST_VECTORS_H

#include <stddef.h>
#include <stdint.h>

/**
 * @brief Test vector for BLE advertisement encryption
 */
struct ble_adv_test_vector {
	const char *description; /* Human-readable test case name */
	uint32_t time_counter;   /* Time counter value */
	uint16_t seq_no;         /* Sequence number */
	const uint8_t *payload;  /* Cleartext payload input */
	size_t payload_len;      /* Payload length (0-13) */
	const uint8_t *expected; /* Expected BLE advertisement output */
	size_t expected_len;     /* Expected output length */
};

/* Test vectors generated by tools/ble-adv-vectors.py */
extern const struct ble_adv_test_vector test_vectors[];
extern const size_t test_vectors_count;

#endif /* TEST_VECTORS_H */
